 function f=calculate_frf(obj)
            f_min = max(...
                0,...
                min(obj.f_center*(1-obj.tx_bandwidth),...
                    obj.f_center*(1-obj.iso_bandwidth)));
            f_max= max(...
                obj.f_center*(1+obj.iso_bandwidth),...
                obj.f_center*(1+obj.tx_bandwidth));
            f=linspace(f_min,f_max,obj.fpoints);

    end
