function Z_odd=get_Z_odd(obj,freq)

q=obj.get_q(freq);

Z_odd = obj.get_Z_line * ...
    sqrt ( obj.get_epsilon_eff /...
            obj.get_epsilon_odd(0) ) /...
    (1 - q(10) * sqrt( obj.get_epsilon_eff ) * ...
    obj.get_Z_line/377 ) ;

end
